### ISSUE TITLE
Frontend-Sprint #1

### ISSUE THREAD

**Issue by ogchectoco** [JUSTADDMETA/justaddmeta-minting-dapp#12]
- Update Landing Page as displayed in Figma
- Approve Asset is not spinning -> can be removed -> minting nft as a indicator is fine 
- Mint Amount indicator is on the wrong page -> should be on minting interface
- Footer is outdated please update as displayed in Figma
- Add Social-Links to Footer
- Add Social-Icons to Footer
- Button in Footer should lead to -> justaddmeta.com 
- JUSTADDMETA Logo leads to homepage
- Please replace JUSTADDMETA written in letters with our logo 
- Add image container to wallet-connect page
- Add checkout page as displayed in figma
- Remove Tool tip after minting and display sucess message in content as displayed in figma
- Rename asset purchase to Mint NFT
- Add Fav-Icon 
- Rename Page from Alpha Minting to SUMMERJAM
- Add position:fixed to nav to make it sticky
- Add hover-state to button as displayed in figma
- Add transition after "layout switch"

**Comment by streamerd** [comment]
hey @ogchectoco here's the status update. 
✅   Update Landing Page as displayed in Figma
✅  Approve Asset is not spinning -> can be removed -> minting nft as a indicator is fine
    Mint Amount indicator is on the wrong page -> should be on minting interface
✅   Footer is outdated please update as displayed in Figma
    Add Social-Links to Footer
    Add Social-Icons to Footer
✅ Button in Navigation should lead to -> justaddmeta.com 
    Please replace JUSTADDMETA written in letters with our logo
✅ Add image container to wallet-connect page
     Add checkout page as displayed in figma
✅  Remove Tool tip after minting and display sucess message in content as displayed in figma
✅  Rename asset purchase to Mint NFT
    Add Fav-Icon
 ✅   Rename Page from Alpha Minting to SUMMERJAM
 ✅  Add position:fixed to nav to make it sticky
    Add hover-state to button as displayed in figma
    Add transition after "layout switch"

**Comment by streamerd** [comment]
✅ Mint Amount indicator is on the wrong page -> should be on minting interface

🍳 cooking the checkout page. now we're getting txHash and generating etherscan link ~ which soon will become polygonscan link after we switch network 

https://github.com/JUSTADDMETA/justaddmeta-minting-dapp/pull/14

**Comment by ogchectoco** [comment]
Done
